/**
 * Every image on the site, with its alt text. Entries with `placeholder: true` are stand-in illustrations
 * (generated by scripts/generate-placeholder-images.mjs) shown with a badge until the real photo or screenshot
 * arrives. To use a real image: add it under public/images/, change `src`, and delete `placeholder`.
 */
export type SiteImageData = { src: string; alt: string; placeholder?: true };

const ph = (name: string) => `/images/placeholders/${name}.svg`;

export const images = {
  // From the old site's Team page (343×444). Content decision L1: ask for a high-resolution original.
  founder: { src: "/images/team/muttu-sarashetti.jpg", alt: "Muttu Sarashetti, Founder and CEO of Texiri Solutions" },

  consultingTeam: { src: ph("consulting-team"), alt: "Texiri SAP consultants reviewing an S/4HANA migration plan with a client team", placeholder: true },
  teamPhoto: { src: ph("team-photo"), alt: "The Texiri team at the Vijayapura office", placeholder: true },
  office: { src: ph("office"), alt: "The Texiri Solutions office building in Vijayapura", placeholder: true },
  dataMigration: { src: ph("data-migration"), alt: "Data from ECC, legacy systems and Excel being cleansed and validated before loading into S/4HANA", placeholder: true },
  klicksUi: { src: ph("2klicks-ui"), alt: "2Klicks Create screen: a lease-contract template with a custom field, and a validation log ready to load", placeholder: true },
  aiWorkshop: { src: ph("ai-workshop"), alt: "A client team in an AI readiness workshop, looking at a ranked map of use cases", placeholder: true },
  communityWorkshop: { src: ph("community-workshop"), alt: "TEXIRI AI Community members at a hands-on prompting workshop", placeholder: true },
  communityDemo: { src: ph("community-demo"), alt: "A community member presenting their first chatbot project", placeholder: true },
  projectVision: { src: ph("project-vision"), alt: "Member project: a computer-vision model labelling a car and a person", placeholder: true },
  projectChatbot: { src: ph("project-chatbot"), alt: "Member project: a chatbot recommending a learning path", placeholder: true },
  projectForecast: { src: ph("project-forecast"), alt: "Member project: a weekly demand forecast chart", placeholder: true },
  articleEcc: { src: ph("article-ecc-2027"), alt: "Illustration: a calendar showing December 2027 next to a clock", placeholder: true },
  articleRefx: { src: ph("article-refx"), alt: "Illustration: office buildings and a lease document", placeholder: true },
  articleAi: { src: ph("article-first-ai"), alt: "Illustration: three AI use cases ranked one to three", placeholder: true },
  learners: { src: ph("learners"), alt: "Shambhavi 108 learners restarting their careers, coding on laptops", placeholder: true },
} satisfies Record<string, SiteImageData>;
